### ISSUE TITLE
Omz not cloning

### ISSUE THREAD

**Issue by Sharmapankaj5432** [adi1090x/termux-omz#10]
![Screenshot_2022-04-30-17-56-10-951_com.termux.jpg](https://user-images.githubusercontent.com/93596216/166105494-638d61cb-8659-4099-878f-32ba3c024bbb.jpg)

**Comment by je4npw** [comment]
Bad for me :(

![Screenshot_20221030-060919_Termux.jpg](https://user-images.githubusercontent.com/8014939/198871025-63f9dee1-a290-43e1-83a5-bffb5ba10412.jpg)

**Comment by Gulshan0** [comment]
> Bad for me :(
> 
> ![Screenshot_20221030-060919_Termux.jpg](https://user-images.githubusercontent.com/8014939/198871025-63f9dee1-a290-43e1-83a5-bffb5ba10412.jpg)

Same here :/

**Comment by cash-4au** [comment]
Same for me

![Screenshot_2023-05-12-18-19-24-37_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/adi1090x/termux-omz/assets/43421762/8671875f-5e0c-4e14-a58c-311a391e089b)
