### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by Subhankar2000** [adi1090x/termux-omz#3]

**Comment by forliuyifei** [comment]
Same question.

**Comment by Subhankar2000** [comment]
I think after following these steps, termux should be back to normal to some extent
Steps : 
--------------------------------

cd ~/
rm .termux/colors.properties
rm .termux/font.ttf
rm .zshrc
rm -r .oh-my-zsh
chsh -s bash

--------------------------------
I think this script did not install anything new as particular(it installed zsh which is just a termux repo package) other than just copying config files here and there and modifying .zshrc, resulting in change of colour and font, executing the above will revert to default colour and font and to default bash shell (and even to default zsh config if you want), apart from this you can also just remove zsh by simply 'apt remove zsh'.

**Comment by ListsJohnson** [comment]
Thanks a lot, it worked 💪
