### ISSUE TITLE
How do you add color to commands?

### ISSUE THREAD

**Issue by rypz79** [adi1090x/termux-omz#6]
As shown in OMZ default
`ZSH_THEME="robbyrussell`
![70f58fb6-ba03-11e4-82c9-c083bf9a6574](https://user-images.githubusercontent.com/28814757/106768256-68621600-6644-11eb-9c39-c4285f043c6a.png)
cd, gco, touch etc...

Also su (root user) is not handled (returns to regular bash theme). Tried `su -s` and it's missing an argument. 

TNX

**Comment by shdbwa** [comment]
https://github.com/zdharma/fast-syntax-highlighting
