### ISSUE TITLE
unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by Smithy191076** [adi1090x/termux-omz#9]
Cannot install, how to fix please?
![Screenshot_20220316-110125_Termux](https://user-images.githubusercontent.com/74907332/158576668-1a0931b8-3c97-4cdd-8ecd-2ebcb6672fa4.jpg)

**Comment by dhdgves** [comment]
This problem occur because of the script "install" in line 76. Just change the protocol from "git://" to "https://" in the line 76, and run the script you have changed, everything will be fine.

**Comment by hafidzaini** [comment]
> This problem occur because of the script "install" in line 76. Just change the protocol from "git://" to "https://" in the line 76, and run the script you have changed, everything will be fine.
> 
> If you like, you could try my modified script, forked from this repo , in [this](https://github.com/dhdgves/termux-omz).

same error 😰

**Comment by hafidzaini** [comment]
solve this issue by command

git config --global url."https://".insteadOf git://

**Comment by dominic-salvador** [comment]
It's working! Just copy paste the above command verbatim into the cloned repository. Thank you!!
Screenshot:
[Screenshot_2022-06-07-15-25-57-431_com.termux.jpg](https://user-images.githubusercontent.com/94506586/172321170-44666173-63db-4342-8e58-fb82f426eaee.jpg)
